apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-feed
  name: frontend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-feed
  template:
    metadata:
      labels:
        service: frontend-feed
    spec:
      containers:
      - image: 120819911993/udagram-frontend
        name: frontend-feed
        imagePullPolicy: Always 
        ports:
        - containerPort: 80 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        
      restartPolicy: Always
     