apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy-feed
  name: reverseproxy-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy-feed
  template:
    metadata:
      labels:
        service: reverseproxy-feed
    spec:
      containers:
      - image: 120819911993/udagram-reverseproxy
        name: reverseproxy-feed
        imagePullPolicy: Always  
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        
      restartPolicy: Always
     